
services:
  app:
    container_name: mopl-app
    # 🔥 [수정] 아까 코드(RedisConfig) 고치고 새로 올린 이미지 버전으로 꼭 변경해주세요!
    # 예: 1.0.0 -> 1.0.2
    image: 935595347062.dkr.ecr.ap-northeast-2.amazonaws.com/dev/my-repo:mopl-management-app-1.0.4
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod

      SPRING_CLOUD_AWS_S3_BUCKET: mopl-server-bucket-247128

      # [핵심] 이제 Java 코드(RedisConfig)가 이 값을 읽어서 'redis' 컨테이너로 접속합니다.
      SPRING_DATA_REDIS_HOST: master.mopl-elasticache-cach.8rmfef.apn2.cache.amazonaws.com
      SPRING_DATA_REDIS_PORT: 6379

      # 아래 사용자 정의 변수는 Java 코드에서 안 쓴다면 지워도 되지만, 둬도 상관없습니다.
      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      SPRING_BATCH_JDBC_INITIALIZE_SCHEMA: never
      # [핵심] DB 초기화 방지
      SPRING_SQL_INIT_MODE: never
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

      SPRING_BATCH_JOB_ENABLED: false

    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    container_name: mopl-redis
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  redis_data: