spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: true
      timeout: 3s

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.tool.schema: debug
    org.springframework.jdbc.datasource.init: debug
    org.springframework.web: info
